# Generated by Django 3.0.8 on 2020-09-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0002_auto_20200929_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('user_id', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('login_type', models.CharField(default='signin', max_length=20)),
            ],
        ),
    ]
