# Generated by Django 3.0.8 on 2020-09-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0003_userr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userr',
            name='Favourite',
            field=models.CharField(default='', max_length=100),
        ),
    ]
